Repository dwightjack/vue-types, pull requests merged in 2021-08, with the labels that each got.

#158 fix: shim.ts BaseVueTypes.extend need support Array props
  __tests__/shim.test.ts
  src/shim.ts
Labels: fix

#156 Add log level for `warn`
  __tests__/jest.setup.js
  __tests__/utils.test.ts
  docs/guide/configuration.md
  package-lock.json
  package.json
  renovate.json
  src/config.ts
  src/types.d.ts
  src/utils.ts
Labels: enhancement

#153 Review shim DX
  .eslintignore
  .gitignore
  docs/guide/installation.md
  nuxt/module.js
  nuxt/package.json
  package-lock.json
  package.json
  shim/package.json
Labels: enhancement

#162 fix: customType can not to be get multiple times because of redefine…
  __tests__/shim.test.ts
  src/shim.ts
Labels: bug

#164 CI: workflow improvements
  .github/workflows/build.yml
  .github/workflows/gh-pages.yml
Labels: enhancement
